---
stocks:
  C2cx:
    BTC_CNY:
      active: true
      visible: false
    ETH_CNY:
      active: true
      visible: false
    ETC_CNY:
      active: true
      visible: false
    SKY_CNY:
      active: false
    ETH_BTC:
      active: false
      visible: true
      cross: true
      base_pair: BTC_CNY
      target_pair: ETH_CNY
    ETC_BTC:
      active: false
      visible: true
      cross: true
      base_pair: BTC_CNY
      target_pair: ETC_CNY
